# Generated by Django 3.0.6 on 2020-09-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='phone',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
