# Generated by Django 3.0.6 on 2020-09-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20200910_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='power',
        ),
        migrations.AddField(
            model_name='car',
            name='fueltype',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='trim',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
